import type { ArtType, SpecialForm, Vibe } from "./types";

export const ART_TYPE_ICONS: Record<ArtType, string> = {
  ex: "⚔️",
  "illustration-rare": "🌟",
  "special-illustration-rare": "💎",
};

export const SPECIAL_FORM_ICONS: Record<SpecialForm, string> = {
  none: "●",
  shiny: "✨",
  mega: "🔆",
  "gold-star": "⭐",
  "tag-team": "🤝",
  ancient: "🦴",
  future: "🤖",
  "delta-species": "δ",
  alolan: "🌺",
  galarian: "⚔️",
  hisuian: "🏮",
  paldean: "🍇",
};

export const VIBE_ICONS: Record<Vibe, string> = {
  cozy: "🕯️",
  menacing: "😈",
  serene: "🕊️",
  chaotic: "🌀",
  majestic: "👑",
  playful: "🎈",
  melancholic: "🌧️",
  triumphant: "🏆",
  mysterious: "🌫️",
  electric: "⚡",
  dreamy: "💭",
  fierce: "🔥",
  nostalgic: "📻",
  ethereal: "🌌",
  rebellious: "🤘",
  wholesome: "🌻",
  ominous: "⛈️",
  vibrant: "🌈",
  tranquil: "🌊",
  epic: "🎬",
  regal: "🏛️",
  whimsical: "🎪",
  haunting: "👻",
  radiant: "☀️",
  stormy: "🌩️",
  intimate: "🕯️",
  explosive: "💥",
  frosty: "❄️",
  sultry: "🌹",
  solemn: "🕊️",
  curious: "🔍",
  celestial: "🌠",
  industrial: "⚙️",
  enchanted: "🧚",
  desolate: "🏜️",
  jubilant: "🎉",
  brooding: "🌑",
  surreal: "🌀",
  vengeful: "🗡️",
  glorious: "🌅",
  idyllic: "🌄",
  feverish: "🥵",
  reverent: "🙏",
  vigilant: "👁️",
  opulent: "💰",
  delirious: "🥴",
  zealous: "🔱",
  clandestine: "🕵️",
  feral: "🐺",
  festive: "🎊",
  primeval: "🗿",
  austere: "⬜",
  macabre: "💀",
  buoyant: "🫧",
  volcanic: "🌋",
  untethered: "🎐",
  resolute: "🛡️",
  chivalrous: "🐴",
  voracious: "🦈",
  prophetic: "🔮",
};
